### ISSUE TITLE
Erro no boleto

### ISSUE THREAD

**Issue by richard-nexxus** [gamuzabrasil/gamuza_itaushopline-magento#2]
Boa Tarde,

Estou com um problema no itau shopline, quando finalizo o pedido e vou gerar o boleto o mesmo quando redirecionado a tela do Itau shopline apresenta a mensagem "data ou valor do boleto diferem do registro original"

Sabe o que pode estar ocorrendo?
Agradeço desde já

**Comment by eneiasramos** [comment]
Olá! @richard-nexxus !

Qual a URL da sua loja?

Att,

**Comment by richard-nexxus** [comment]
Olá @eneiasramos 

www.cabelosnet.com.br

**Comment by eneiasramos** [comment]
Olá @richard-nexxus ! Tudo bem?

Não tivemos problemas ao efetuar um pedido de testes na loja:

![cabelosnet-gamuza-itaushopline-pagina-sucesso-pedido](https://cloud.githubusercontent.com/assets/2862728/15748144/0aad63de-28b4-11e6-87d1-c843f4cda21c.png)

![cabelosnet-gamuza-itaushopline-boleto](https://cloud.githubusercontent.com/assets/2862728/15748143/0aa4b298-28b4-11e6-9021-6bd2cdd1b957.png)
