### ISSUE TITLE
Problemas na criptografia ou o campo pedido está incorreto.

### ISSUE THREAD

**Issue by yurirn** [gamuzabrasil/gamuza_itaushopline-magento#24]
Boa noite, estou com problema para consultar o pagamento do boleto, quando clico para consultar, aparece essa mensagem

**Problemas na criptografia ou o campo pedido está incorreto.**

![Capturar](https://user-images.githubusercontent.com/17936919/103592034-a4cd1580-4ed0-11eb-9541-50820af143d4.PNG)

**Comment by eneiasramos** [comment]
@yurirn tudo bem?

Essa mensagem de erro aparece devido a configurações incorretas em sua loja.

Por favor, verifique:

- Código do Itaú Shopline (Devem estar em letras maiúsculas)
- Chave do Itaú Shopline (Devem estar em letras maiúsculas)
- Dias para expiração do boleto
- Campo de CPF ou CNPJ do cliente.
- Campos de Endereço e Bairro (Deve estar configurado 2 campos para endereço no painel administrativo)
- Campos de CEP, Cidade e Estado.

A URL de retorno deve conter um endereço seguro para uma página de sucesso de sua loja.

Ex: https://www.minhaloja.com.br/checkout/onepage/success

Qualquer dúvida estamos a disposição.

Att,
