### ISSUE TITLE
Tabela Não criada no DB

### ISSUE THREAD

**Issue by grupouweb** [gamuzabrasil/gamuza_itaushopline-magento#3]
Olá Eneias,
Boa tarde!
Chequei no forum e não achei nenhum tópico semelhante, por isso abri por aqui:

Instalei os 2 módulos "Utils e Itaú Shop line" (baixados pelo Github) e agora minha loja reporta alguns erros ao clicar no Gamuza através do Admin da loja Gerenciar transações do Itau Shop Line dizendo que não tem a tabela no banco de dados:

`a:5:{i:0;s:310:"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'planeta_2017.gamuza_itaushopline_transactions' doesn't exist, query was: SELECT COUNT(*) FROM `gamuza_itaushopline_transactions` AS `main_table`
 INNER JOIN `sales_flat_order` AS `table_sales_order` ON main_table.order_id = table_sales_order.entity_id";i:1;s:5945:"#0 /home/planeta/public_html/2017/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /home/planeta/public_html/2017/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /home/planeta/public_html/2017/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /home/planeta/public_html/2017/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT COUNT(*)...', Array)
#4 /home/planeta/public_html/2017/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('SELECT COUNT(*)...', Array)
#5 /home/planeta/public_html/2017/lib/Zend/Db/Adapter/Abstract.php(828): Varien_Db_Adapter_Pdo_Mysql->query(Object(Varien_Db_Select), Array)
#6 /home/planeta/public_html/2017/lib/Varien/Data/Collection/Db.php(225): Zend_Db_Adapter_Abstract->fetchOne(Object(Varien_Db_Select), Array)
#7 /home/planeta/public_html/2017/lib/Varien/Data/Collection.php(225): Varien_Data_Collection_Db->getSize()
#8 /home/planeta/public_html/2017/lib/Varien/Data/Collection.php(211): Varien_Data_Collection->getLastPageNumber()
#9 /home/planeta/public_html/2017/lib/Varien/Data/Collection/Db.php(522): Varien_Data_Collection->getCurPage()
#10 /home/planeta/public_html/2017/lib/Varien/Data/Collection/Db.php(569): Varien_Data_Collection_Db->_renderLimit()
#11 /home/planeta/public_html/2017/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(533): Varien_Data_Collection_Db->load()
#12 /home/planeta/public_html/2017/app/code/local/Gamuza/Itaushopline/Block/Adminhtml/Transactions/Grid.php(52): Mage_Adminhtml_Block_Widget_Grid->_prepareCollection()
#13 /home/planeta/public_html/2017/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(626): Gamuza_Itaushopline_Block_Adminhtml_Transactions_Grid->_prepareCollection()
#14 /home/planeta/public_html/2017/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(632): Mage_Adminhtml_Block_Widget_Grid->_prepareGrid()
#15 /home/planeta/public_html/2017/app/code/core/Mage/Core/Block/Abstract.php(918): Mage_Adminhtml_Block_Widget_Grid->_beforeToHtml()
#16 /home/planeta/public_html/2017/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#17 /home/planeta/public_html/2017/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('grid', true)
#18 /home/planeta/public_html/2017/app/code/core/Mage/Adminhtml/Block/Widget/Grid/Container.php(77): Mage_Core_Block_Abstract->getChildHtml('grid')
#19 /home/planeta/public_html/2017/app/design/adminhtml/default/default/template/widget/grid/container.phtml(36): Mage_Adminhtml_Block_Widget_Grid_Container->getGridHtml()
#20 /home/planeta/public_html/2017/app/code/core/Mage/Core/Block/Template.php(241): include('/home/planeta/p...')
#21 /home/planeta/public_html/2017/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#22 /home/planeta/public_html/2017/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#23 /home/planeta/public_html/2017/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#24 /home/planeta/public_html/2017/app/code/core/Mage/Adminhtml/Block/Widget/Container.php(308): Mage_Adminhtml_Block_Template->_toHtml()
#25 /home/planeta/public_html/2017/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Widget_Container->_toHtml()
#26 /home/planeta/public_html/2017/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#27 /home/planeta/public_html/2017/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#28 /home/planeta/public_html/2017/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#29 /home/planeta/public_html/2017/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#30 /home/planeta/public_html/2017/app/design/adminhtml/default/default/template/page.phtml(74): Mage_Core_Block_Abstract->getChildHtml('content')
#31 /home/planeta/public_html/2017/app/code/core/Mage/Core/Block/Template.php(241): include('/home/planeta/p...')
#32 /home/planeta/public_html/2017/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#33 /home/planeta/public_html/2017/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#34 /home/planeta/public_html/2017/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#35 /home/planeta/public_html/2017/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#36 /home/planeta/public_html/2017/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#37 /home/planeta/public_html/2017/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#38 /home/planeta/public_html/2017/app/code/local/Gamuza/Itaushopline/controllers/Adminhtml/TransactionsController.php(42): Mage_Core_Controller_Varien_Action->renderLayout()
#39 /home/planeta/public_html/2017/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Gamuza_Itaushopline_Adminhtml_TransactionsController->indexAction()
#40 /home/planeta/public_html/2017/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#41 /home/planeta/public_html/2017/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#42 /home/planeta/public_html/2017/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#43 /home/planeta/public_html/2017/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#44 /home/planeta/public_html/2017/index.php(83): Mage::run('', 'store')
#45 {main}";s:3:"url";s:90:"/index.php/itaushopline/adminhtml_transactions/index/key/45f94d17ccfe7e606124277505241c03/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}`

URL testes: http://2017.planetapc.com.br/

Agradeço à atenção!
Abraco!

**Comment by eneiasramos** [comment]
Olá @grupouweb ! Tudo bem?

Por favor, siga os passos descritos abaixo:

- Baixe a versão mais recente do módulo em nosso canal do github: http://github.com/gamuzabrasil

- Acesse sua base de dados e exclua o registro que contenha itaushopline_setup na tabela core_resource.

- Limpe todos os caches

Att,
