### ISSUE TITLE
Botão na página de Sucesso...

### ISSUE THREAD

**Issue by grupouweb** [gamuzabrasil/gamuza_itaushopline-magento#4]
Olá Eneias,
Boa noite!
Já fiz os passos abaixo mas não obtive exito com o botão na pagina de sucesso para o Itau shop Line...

Tem alguma ideia do que pode ser?

No admin, no frontend na parte dos pedidos e nos e-mails o link aparece ok!

Grato!
====================================================
- O botão PAGAR não está sendo exibido na página de sucesso

Você usa algum tema customizado em sua loja? Talvez isso pode estar ocasionando o seu problema...

Tente copiar os arquivos do tema default para o seu tema:

app/design/frontend/base/default/layout/gamuza/utils.xml
app/design/frontend/base/default/template/gamuza/utils
app/design/frontend/base/default/template/gamuza/itaushopline
Para:

app/design/frontend/pacote/tema/layout/gamuza/utils.xml
app/design/frontend/pacote/tema/template/gamuza/utils
app/design/frontend/pacote/tema/template/gamuza/itaushopline

====================================================

**Comment by eneiasramos** [comment]
Olá @grupouweb ! Tudo bem?

Qual checkout você está utilizando?

Tem alguma URL de testes da loja?

Att,

**Comment by grupouweb** [comment]
Tudo bem e vc?

A URL de testes é: http://www.maislediluminacao.com.br/

Estou usando o OSC do Deivison Arthur...

Abraço e obrigado!

**Comment by eneiasramos** [comment]
Olá @grupouweb ! Tudo bem?

Percebemos que você está utilizando o módulo BoletoBancario do MagentoBR em sua loja virtual.

Este módulo sempre gera problemas, pois substitui o template padrão do magento, impedindo exibição das informações na página de sucesso do pedido.

Sugerimos que utilize o nosso módulo de Boletos que funcionará sem problemas em sua loja virtual: https://github.com/gamuzabrasil/gamuza_slips-magento

Qualquer dúvida estamos a disposição!

Att,
