### ISSUE TITLE
Problema Boleto e dúvida

### ISSUE THREAD

**Issue by cfgalvani** [gamuzabrasil/gamuza_itaushopline-magento#5]
1. O cliente finaliza a compra normalmente, mas no site do Itaú quando peço pra imprimir o boleto, sou redirecionado para a página https://shopline.itau.com.br/shopline/Impressao.aspx que fica em branco. No Painel em Gerenciar Transações do Itaú Shopline consigo consultar o pedido normalmente:
![itaushopline-magento](https://cloud.githubusercontent.com/assets/12137704/21104469/bc38a1b2-c06d-11e6-8658-f41ac249b37d.jpg)
A integração foi feita dia 09/12.

2. O retorno já é automático ou preciso configurar manualmente e adicionar a URL no campo correspondente no painel do magento?

**Comment by eneiasramos** [comment]
Olá @cfgalvani ! Tudo bem?

Se o cadastro no Shopline é recente, deve aguardar até 48 horas para utilizá-lo.

O retorno automático não está disponível na versão gratuita e a URL é necessária somente para utilizar uma página de sucesso customizada.

Att,
