### ISSUE TITLE
Como preencho corretamente a URL de retorno?

### ISSUE THREAD

**Issue by fernandoperigolo** [gamuzabrasil/gamuza_itaushopline-magento#7]
Devo colocar a URL completa com HTTPS? Só o domínio? ou só /checkout/cart/success?

**Comment by eneiasramos** [comment]
Olá @fernandoperigolo ! Tudo bem?

O uso da URL customizada se faz necessário somente se você tem uma página de sucesso customizada. Se tiver deve preencher o endereço completo em HTTPS.

Ex: www.minhaloja.com.br/minha/pagina/sucesso

Att,
