### ISSUE TITLE
Duplo clique para finalizar a compra usando OSC

### ISSUE THREAD

**Issue by fernandoperigolo** [gamuzabrasil/gamuza_itaushopline-magento#9]
Quando se usa o OSC, depois que o cliente preenche os dados do cartão, ele vai direto no botão Finalizar Compra. Neste momento, o bloco de Review recarrega e o cliente tem que clicar novamente no Finalizar Compra.

Isso acontece quando o cliente não seleciona um parcelamento, já que já vem preenchido. Mas para o Magento, como o cliente não clicou e escolheu uma opção, é como se não tivesse preenchido e por isso, depois de preencher todos os dados do cartão, o bloco de review não é atualizado.

Eu resolvi este problema colocando uma opção no select de parcelas com value vazio e tornando o campo required. Assim o campo vem sempre vazio e o cliente é obrigado a preencher.

Não sei se teria outra forma de resolver isso. Caso alguém ache interessante e já tenha passado por isso me aviso que compartilho em detalhes o que eu fiz.

**Comment by fernandoperigolo** [comment]
Nossa, eu simplesmente criei esta issue no projeto errado.

**Comment by apzeiro** [comment]
@fernandoperigolo Joga essa issue lá no OSC que pode ter mais gente com o mesmo problema.
